### ISSUE TITLE
Possible Progressive Shield Glitch

### ISSUE THREAD

**Issue by klaus3481** [tewtal/alttp_sm_combo_randomizer#33] opened 2018-06-08 21:03 UTC
Console or Emulator: Emulator, lr-snes9x2010

 If emulator state which emulator and version.

Original Filename: SMALttP - sm-casual_alttp-no-glitches-v9.2_normal-open_morph-randomized_ganon_combo_297779084.sfc

Seed: 297779084

ALTTP Logic: alttp-no-glitches-v9.2
SM Logic: sm-casual
ROM build: 2018-05-29
Difficulty: normal
Variation: combo
Mode: open
Morph: randomized
Goal: ganon

Description of problem: In the room where the reserve tank and missile upgrades are normally in Norfair, there are instead two progressive shield upgrades. I collected them both, but it didn't upgrade me to the Red Shield. I don't recall the mirror shield being needed to complete the game, but would this lock me out of getting the mirror shield?

Spoiler (if available): Reserve Tank, Norfair | Progressive Shield
-- | --
Missile (Norfair Reserve Tank) | Progressive Shield

**Comment by tewtal** [comment] 2018-07-15 22:18
This is the same issue as #31.
Closing this issue for now since it's a duplicate of that one.

**Closed by tewtal** 2018-07-15 22:18 UTC
